# Generated by Django 3.2.6 on 2021-08-27 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0003_truck_current_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rates', models.CharField(blank=True, max_length=10)),
                ('tonnages', models.FloatField(help_text=' tons ')),
                ('created', models.DateField(blank=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.truck')),
            ],
        ),
    ]
