# Generated by Django 3.2.6 on 2021-08-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0004_alter_position_delivery_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='Delivery_Number',
        ),
    ]
