# Generated by Django 3.2.6 on 2021-08-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210827_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='current_rates',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
