# Generated by Django 3.2.6 on 2021-08-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_truck_delivery_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='Delivery_Number',
        ),
    ]
